/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sbs.projects;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.openfeign.EnableFeignClients;
import org.springframework.context.annotation.ComponentScan;

@EnableFeignClients(basePackages = "com.sbs.contracts.*")
@ComponentScan({"com.sbs.*"})
@SpringBootApplication
public class ProjectsApplication {
    public static void main(String[] args) {
        SpringApplication.run(ProjectsApplication.class, args);
    }
}
