/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package userStories;

import org.junit.Test;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        UserStoriesApplication classUnderTest = new UserStoriesApplication();
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
