/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projects;

public class ProjectsApplication {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new ProjectsApplication().getGreeting());
    }
}
