/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projects;

import org.junit.Test;

import static org.junit.Assert.assertNotNull;

public class ProjectsApplicationTest {
    @Test
    public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
