/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sbs.projects;

import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.test.context.junit4.SpringRunner;

@RunWith(SpringRunner.class)
@ComponentScan(basePackages = "userStories")
@SpringBootTest(classes = ProjectsApplication.class)
public class ProjectsApplicationTest {


}
