/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sbs.projects;

import org.junit.Assert;
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


public class ProjectsApplicationTest {
    private static final Logger logger = LoggerFactory.getLogger(ProjectsApplicationTest.class);

    @Test
    public void simpleTest() {
        logger.info("Simple test");
        Assert.assertEquals(1,1);
    }
}
