INSERT INTO USER_STORY (DESCRIPTION,TITLE,WEIGHT) VALUES ( 'Description 1','Title 1',2);
INSERT INTO USER_STORY (DESCRIPTION,TITLE,WEIGHT) VALUES ( 'Description 2','Title 2',2);
INSERT INTO USER_STORY (DESCRIPTION,TITLE,WEIGHT) VALUES ( 'Description 3','Title 3',2);
INSERT INTO USER_STORY (DESCRIPTION,TITLE,WEIGHT) VALUES ( 'Description 4','Title 4',2);
INSERT INTO USER_STORY (DESCRIPTION,TITLE,WEIGHT) VALUES ( 'Description 5','Title 5',2);
INSERT INTO USER_STORY (DESCRIPTION,TITLE,WEIGHT) VALUES ( 'Description 6','Title 6',2);
INSERT INTO USER_STORY (DESCRIPTION,TITLE,WEIGHT) VALUES ( 'Description 7','Title 7',2);
INSERT INTO USER_STORY (DESCRIPTION,TITLE,WEIGHT) VALUES ( 'Description 8','Title 8',2);
INSERT INTO USER_STORY (DESCRIPTION,TITLE,WEIGHT) VALUES ( 'Description 9','Title 9',2);
INSERT INTO USER_STORY (DESCRIPTION,TITLE,WEIGHT) VALUES ( 'Description 10','Title 10',2);

INSERT INTO LABEL(DESCRIPTION) VALUES('Historia Funcional');
INSERT INTO LABEL(DESCRIPTION) VALUES('Historia Tecnica');
